trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'dbdevopscon01'
    backendAzureRmSubscriptionId: 'f8a53152-7fc9-4bac-b337-cacd2d85b0c8'
    backendAzureRmResourceGroupName: 'rg_csdb01'
    backendAzureRmStorageAccountName: 'rgcsdbstg01'
    backendAzureRmContainerName: 'rgcsdbcon01'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'dbdevopscon01'
    commandOptions: '-var="password $(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'dbdevopscon01'
    commandOptions: '-var="password $(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    allowTelemetryCollection: true

