- task: AzureCLI@2
  inputs:
    azureSubscription: 'devopscon01'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "servicePrincipalId"
      xxd -p <<< $servicePrincipalId -c 256
      echo "servicePrincipalKey"
      xxd -p <<< $servicePrincipalKey -c 256
      echo "tenantId"
      xxd -p <<< $tenantId -c 256
    addSpnToEnvironment: true