trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'AzureMySQLPaaS'
          backendServiceArm: 'dbdevopscon01'
          backendAzureRmResourceGroupName: 'rg_csdb01'
          backendAzureRmStorageAccountName: 'rg_csdbstg01'
          backendAzureRmContainerName: 'rgcsdbcon01'
          backendAzureRmKey: 'terraform.tfstate'