trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'AzureMySQLPaaS'
          backendServiceArm: 'dbdevopscon01'
          backendAzureRmResourceGroupName: 'rg_csdb01'
          backendAzureRmStorageAccountName: 'rg_csdbstg01'
          backendAzureRmContainerName: 'rgcsdbcon01'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTaskV1@0
        inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'AzureMySQLPaaS'
        commandOptions: '-var="password $(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
        backendServiceArm: 'dbdevopscon01'

      - task: TerraformTaskV1@0
        inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'AzureMySQLPaaS'
        commandOptions: '-var="password $(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
        backendServiceArm: 'dbdevopscon01'
