trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'devopscon01'
    backendAzureRmResourceGroupName: 'rg_csdb01'
    backendAzureRmStorageAccountName: 'rgcsdbstg01'
    backendAzureRmContainerName: 'rgcsdbcon01'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    backendServiceArm: 'devopscon01'
    commandOptions: '-var="password=$(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    backendServiceArm: 'devopscon01'
    commandOptions: '-var="password=$(SQL_PASSWORD)" -var="ip_address=$(IP_ADDRESS)"'
    allowTelemetryCollection: true
